kv/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('countries.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<pk>\d+)/$', 'country', name='country'),
    url(r'^help/$', 'help_page', name='help'),
    url(r'^add/$', 'add_page', name='add'),
    url(r'^upload/$', 'upload', name='upload'),
    url(r'^update_prices/$', 'update_prices', name='update_prices'),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

countries/models.py
# coding=utf-8
from django.db import models


class Country(models.Model):
    RATING_HELP = u'место в рейтинге, чем меньше, тем лучше'

    name = models.CharField(u'Страна', max_length=255, db_index=True)

    # Visas
    business = models.TextField(u'Бизнес иммиграция', null=True, blank=True)
    investor = models.TextField(u'ПМЖ для инвесторов', null=True, blank=True)
    pension = models.TextField(u'Рантье', null=True, blank=True)
    visa_run = models.TextField(u'Visa-run', null=True, blank=True)
    specialist = models.TextField(u'Профессиональная иммиграция', help_text=u'Балльная система либо признние диплома', null=True, blank=True)

    visa_free_default = models.PositiveSmallIntegerField(u'Виза по прилету - срок', null=True, blank=True)
    visa_free_max = models.PositiveSmallIntegerField(u'Виза по прилету - до скольки продлевается', null=True, blank=True)
    residence_min = models.PositiveSmallIntegerField(u'Стоимость резиденции', null=True, blank=True, help_text=u'Самый дешевый вариант ПМЖ (не студент, не виза-раны)')
    residence_min_description = models.TextField(u'Описание дешевой резиденции', null=True, blank=True)

    # Ratings
    happiness = models.PositiveSmallIntegerField(u'Международный индекс счастья', help_text=RATING_HELP, null=True, blank=True)
    prosperity = models.PositiveSmallIntegerField(u'Prosperity Index Rank', help_text=RATING_HELP, null=True, blank=True)
    medicine = models.PositiveSmallIntegerField(u'Медицина (WHO rank)', help_text=RATING_HELP, null=True, blank=True)
    criminal = models.TextField(u'Криминал', null=True, blank=True)

    # Nature
    summer = models.SmallIntegerField(u'Средняя температура летом', null=True, blank=True)
    winter = models.SmallIntegerField(u'Средняя температура зимой', null=True, blank=True)
    mountains = models.NullBooleanField(u'Горы', blank=True, null=True)
    sea = models.NullBooleanField(u'Море', blank=True, null=True)

    # Prices
    rent = models.PositiveSmallIntegerField(u'Аренда в USD', help_text=u'Дом или квартира среднего уровня', blank=True, null=True)
    numbeo_link = models.URLField(u'Numbeo', blank=True, null=True, help_text=u'Ссылка на столицу в numbeo.com')

    # Transport
    capital_iata = models.CharField(u'IATA code', max_length=32, blank=True, null=True, help_text=u'Для сбора стоимости билетов')
    flight_time = models.PositiveSmallIntegerField(u'Время полета из MOW', blank=True, null=True)
    flight_price = models.PositiveSmallIntegerField(u'Стоимость полета из MOW', blank=True, null=True)
    time_zone = models.SmallIntegerField(u'Часовой пояс', help_text=u'Целое число часов (можно округлить), по Гринвичу', blank=True, null=True)

    # Languages
    language = models.TextField(u'Язык', null=True, blank=True)
    language_english = models.NullBooleanField(u'Понимают английский', blank=True, null=True, help_text=u'50+% населения могут объясниться на английском')
    language_russian = models.NullBooleanField(u'Понимают русский', blank=True, null=True, help_text=u'50+% населения могут объясниться на русском')

    # Other
    additional = models.TextField(u'Дополнительные плюшки', null=True, blank=True)

    def time_shift(self):
        if self.time_zone is not None:
            return abs(self.time_zone - 4)
        else:
            return

    @models.permalink
    def get_absolute_url(self):
        return 'country', [self.pk]

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Blog(models.Model):
    country = models.ForeignKey(Country)
    url = models.URLField(u'URL')
    name = models.CharField(u'Имя', max_length=255, null=True, blank=True)

    def __unicode__(self):
        return self.name


class Link(models.Model):
    country = models.ForeignKey(Country)
    url = models.URLField(u'URL')
    name = models.CharField(u'Описание', max_length=255, help_text=u'Что за ссылка - МИД, визы, etc')

    def __unicode__(self):
        return self.name

countries/views.py
# coding=utf-8
import os
import re
import decimal
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import ListView, TemplateView, DetailView, View
import requests

from countries.models import Country


class IndexView(ListView):
    model = Country
    template_name = 'index.html'

index = IndexView.as_view()


class CountryView(DetailView):
    model = Country
    template_name = 'country.html'

country = CountryView.as_view()


class HelpView(TemplateView):
    template_name = 'help.html'

help_page = HelpView.as_view()


class AddView(TemplateView):
    template_name = 'add.html'

add_page = AddView.as_view()


class UploadView(TemplateView):
    template_name = 'upload.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated() or not request.user.is_superuser:
            return redirect('index')

        return super(UploadView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        f = request.FILES['xls']

        import openpyxl
        wb = openpyxl.load_workbook(f)
        sheet = wb['Sheet1']

        for r in sheet.range('A4:AA56'):
            name = r[0].value
            if not any([c.value for c in r[1:]]):
                continue

            has_sea = r[13].value and not u'нет' in r[13].value.lower()
            has_mountains = r[12].value and not u'нет' in r[12].value.lower()

            def get_number(s):
                if not s:
                    return None

                if isinstance(s, int):
                    return s

                if isinstance(s, decimal.Decimal):
                    return s

                numbers = re.match('^(\-?\d+)', s)
                if numbers:
                    return numbers.groups()[0]
                else:
                    return None

            try:
                Country.objects.get(name=name)
            except Country.DoesNotExist:
                c = Country.objects.create(
                    name=r[0].value,
                    business=r[1].value or None,
                    investor=r[2].value or None,
                    pension=r[3].value or None,
                    visa_run=r[4].value or None,
                    specialist=r[5].value or None,
                    happiness=get_number(r[6].value),
                    prosperity=get_number(r[7].value),
                    medicine=get_number(r[8].value),
                    criminal=r[9].value or None,
                    summer=get_number(r[10].value),
                    winter=get_number(r[11].value),
                    mountains=has_mountains,
                    sea=has_sea,
                    rent=get_number(r[14].value),
                    language=r[15].value or None,
                    additional=r[16].value or None,
                )
                print 'Created', c

        return redirect('index')

upload = UploadView.as_view()


class UpdatePricesView(View):
    def get(self, request, *args, **kwargs):
        token = os.environ.get('AVIASALES_TOKEN') or request.GET.get('token')
        if not token:
            messages.error(request, 'Incorrect token', extra_tags='danger')
            return redirect('index')

        headers = {"X-Access-Token": token}
        url = "http://api.travelpayouts.com/v1/prices/cheap?currency=USD&origin=MOW&destination=%s"

        for c in Country.objects.exclude(capital_iata__isnull=True):
            r = requests.get(url % c.capital_iata, headers=headers).json()
            tickets = r.get('data', {}).get(c.capital_iata, {}).values()
            if tickets:
                c.flight_price = min([t['price'] for t in tickets])
                c.save()

        messages.success(request, 'Data updated')
        return redirect('index')

update_prices = UpdatePricesView.as_view()

kv/templates/add.html
{% extends "base.html" %}

{% block content %}
    <h1>Добавляем страну</h1>

    <p>
        Пожалуйста, напишите комментарий с названием страны и имеющейся у вас информацией о ней.
    </p>

    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'kudavalit'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

{% endblock content %}

{% block js %}
{% endblock js %}

kv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% if evil %}Пизд.уй!{% else %}Куда валить из.рф?{% endif %}{% if country %} &mdash; {{ country }}{% endif %}</title>

    <meta property="og:title" content="{% if evil %}Пизд.уй!{% else %}Куда валить из.рф?{% endif %}{% if country %} &mdash; {{ country }}{% endif %}"/> <!--Название видео-->
    <meta property="og:url" content="http://{{ request.get_host }}{{ request.path }}" /> <!--Канонический путь к странице-->
    <meta property="og:description" content="Сравнение стран с точки зрения иммиграции"/> <!--Описание видео-->
    <meta property="og:image" content="http://{{ request.get_host }}/static/{% if evil %}bad{% else %}good{% endif %}.png" /> <!--URL заставки видео-->

    <!-- Bootstrap -->
    {% if evil %}
        <link href="//cdnjs.cloudflare.com/ajax/libs/bootswatch/3.2.0+2/slate/bootstrap.min.css" rel="stylesheet">
    {% else %}
        <link href="//cdnjs.cloudflare.com/ajax/libs/bootswatch/3.2.0+2/sandstone/bootstrap.min.css" rel="stylesheet">
    {% endif %}
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.2.3/bootstrap-table.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    <style>
        body {
            padding-top: 70px;
        }

        .table > thead > tr > th {
            text-align: center;
            vertical-align: middle;
        }

        #share-buttons a {
            display: inline-block;
            padding: 15px 0;
        }

        #share-buttons img {
            width: 35px;
            padding: 0 5px;
            border: 0;
            box-shadow: 0;
            display: inline;
        }
    </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">{% if evil %}Пизд.уй!{% else %}Куда валить из.рф?{% endif %}</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}">Страны</a></li>
                <li><a href="{% url 'add' %}">Добавить страну</a></li>
                <li><a href="{% url 'help' %}">Как пользоваться?</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if evil %}
                    <li><a href="http://кудавалитьиз.рф">Добрая версия</a></li>
                {% else %}
                    <li><a href="http://pizd.uy">Злая версия</a></li>
                {% endif %}

                <li id="share-buttons">
                    <!-- I got these buttons from simplesharebuttons.com -->

                    <!-- Facebook -->
                    <a href="http://www.facebook.com/sharer.php?u=http://{{ request.get_host }}{{ request.path }}" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" /></a>

                    <!-- Twitter -->
                    <a href="http://twitter.com/share?url=http://{{ request.get_host }}{{ request.path }}&text={% if country %}{{ country }} &mdash; {% endif %}{% if evil %}Пизд.уй!{% else %}Куда валить из.рф?{% endif %}&hashtags=simplesharebuttons" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" /></a>

                    <!-- Google+ -->
                    <a href="https://plus.google.com/share?url=http://{{ request.get_host }}{{ request.path }}" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/google.png" alt="Google" /></a>

                    <!-- Email -->
                    <a href="mailto:?Subject=Simple Share Buttons&Body=I%20saw%20this%20and%20thought%20of%20you!%20 http://{{ request.get_host }}{{ request.path }}"><img src="http://www.simplesharebuttons.com/images/somacro/email.png" alt="Email" /></a>
                </li>

            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</div>

<div class="container">
    {% for m in messages %}
        <div class="alert alert-{{ m.tags }}">{{ m }}</div>
    {% endfor %}

    {% block content %}
    {% endblock content %}
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.2.3/bootstrap-table.min.js"></script>

{% block js %}
{% endblock js %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55280707-{% if evil %}2{% else %}1{% endif %}', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

kv/templates/country.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ country.name }}</h1>

    <dl>
        {% if country.business %}
            <dt>Бизнес-виза</dt>
            <dd>{{ country.business }}</dd>
        {% endif %}
        {% if country.investor %}
            <dt>Виза инвестора</dt>
            <dd>{{ country.investor }}</dd>
        {% endif %}
        {% if country.pension %}
            <dt>Виза для рантье/пенсионеров</dt>
            <dd>{{ country.pension }}</dd>
        {% endif %}
        {% if country.visa_run %}
            <dt>Visa-run с туристической визой</dt>
            <dd>{{ country.visa_run }}</dd>
        {% endif %}
        {% if country.specialist %}
            <dt>Виза для специалистов</dt>
            <dd>{{ country.specialist }}</dd>
        {% endif %}

        {% if country.visa_free_default %}
            <dt>Безвизовый въезд на</dt>
            <dd>{{ country.visa_free_default }} дней</dd>
        {% endif %}
        {% if country.visa_free_max %}
            <dt>Максимальный срок проживания без визы</dt>
            <dd>{{ country.visa_free_max }}</dd>
        {% endif %}
        {% if country.residence_min %}
            <dt>Самый дешевый ПМЖ</dt>
            <dd>
                ${{ country.residence_min }}
                {% if country.residence_min_description %}<p>{{ residence_min_description }}</p>{% endif %}
            </dd>
        {% endif %}

        {% if country.happiness %}
            <dt><a href="https://ru.wikipedia.org/wiki/Международный_индекс_счастья">Индекс счастья</a></dt>
            <dd>{{ country.happiness }}</dd>
        {% endif %}
        {% if country.prosperity %}
            <dt><a href="http://en.wikipedia.org/wiki/Legatum_Prosperity_Index">Prosperity index</a></dt>
            <dd>{{ country.prosperity }}</dd>
        {% endif %}
        {% if country.medicine %}
            <dt><a href="http://en.wikipedia.org/wiki/World_Health_Organization_ranking_of_health_systems_in_2000">WHO rank</a></dt>
            <dd>{{ country.medicine }}</dd>
        {% endif %}
        {% if country.summer %}
            <dt>Температура летом</dt>
            <dd>{{ country.summer }}</dd>
        {% endif %}
        {% if country.winter %}
            <dt>Температура зимой</dt>
            <dd>{{ country.winter }}</dd>
        {% endif %}
        {% if country.mountains %}
            <dt>Горы</dt>
            <dd>
                {% if country.mountains %}
                    <span class="text-success glyphicon glyphicon-ok"></span>
                {% else %}
                    <span class="text-danger glyphicon glyphicon-remove"></span>
                {% endif %}
            </dd>
        {% endif %}
        {% if country.sea %}
            <dt>Море</dt>
            <dd>
                {% if country.sea %}
                    <span class="text-success glyphicon glyphicon-ok"></span>
                {% else %}
                    <span class="text-danger glyphicon glyphicon-remove"></span>
                {% endif %}
            </dd>
        {% endif %}
        {% if country.rent %}
            <dt>Аренда</dt>
            <dd>${{ country.rent }}</dd>
        {% endif %}
        {% if country.numbeo_link %}
            <dt>Средние цены</dt>
            <dd><a href="{{ country.numbeo_link }}">{{ country.numbeo_link }}</a></dd>
        {% endif %}

        {% if country.flight_time %}
            <dt>Время перелета из Москвы</dt>
            <dd>{{ country.flight_time }}</dd>
        {% endif %}
        {% if country.flight_price %}
            <dt>Стоимость перелета</dt>
            <dd>${{ country.flight_price }}</dd>
        {% endif %}
        {% if country.time_zone %}
            <dt>Разница с Москвой</dt>
            <dd>{{ country.time_shift }}</dd>
        {% endif %}


        {% if country.language %}
            <dt>Язык</dt>
            <dd>{{ country.language }}</dd>
        {% endif %}
        {% if country.language_english %}
            <dt>Понимают английский</dt>
            <dd><span class="text-success glyphicon glyphicon-ok"></span></dd>
        {% endif %}
        {% if country.language_russian %}
            <dt>Понимают русский</dt>
            <dd><span class="text-success glyphicon glyphicon-ok"></span></dd>
        {% endif %}

        {% if country.additional %}
            <dt>Прочее</dt>
            <dd>{{ country.additional }}</dd>
        {% endif %}
    </dl>

    {% if country.link_set.all %}
        <h2>Ссылки</h2>

        <ul>
            {% for b in country.link_set.all %}
                <li><a href="{{ b.url }}">{{ b.name|default:b.url }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if country.blog_set.all %}
        <h2>Блоги</h2>

        <ul>
            {% for b in country.blog_set.all %}
                <li><a href="{{ b.url }}">{{ b.name|default:b.url }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'kudavalit'; // required: replace example with your forum shortname
        var disqus_identifier = 'country-{{ country.pk }}';

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

{% endblock content %}

{% block js %}
{% endblock js %}

kv/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Страны для иммиграции</h1>

    <div style="overflow-y: hidden; margin-right: 15px;"  id="countries_header">
        <table class="table table-bordered" style="background-color: white;">
            <thead>
                <tr>
                    <th rowspan="2">Страна</th>
                    <th colspan="5">Типы виз</th>
                    <th colspan="3">Индексы <small>(меньше - лучше)</small></th>
                    <th colspan="2">Температура</th>
                    <th colspan="2">Природа</th>
                </tr>
                <tr>
                    <th>Бизнес</th>
                    <th>Инвестиции</th>
                    <th>Рантье</th>
                    <th>Visa-run</th>
                    <th>Специалист</th>
                    <th><a href="https://ru.wikipedia.org/wiki/Международный_индекс_счастья">Счастья</a></th>
                    <th><a href="http://en.wikipedia.org/wiki/Legatum_Prosperity_Index">Prosperity</a></th>
                    <th><a href="http://en.wikipedia.org/wiki/World_Health_Organization_ranking_of_health_systems_in_2000">WHO rank</a></th>
                    <th>Летом</th>
                    <th>Зимой</th>
                    <th>Горы</th>
                    <th>Море</th>
                </tr>
            </thead>
            <tbody>
                {% for c in country_list %}
                    <tr>
                        <td><a href="{% url 'country' c.pk %}">{{ c.name }}</a></td>
                        <td class="text-center">
                            {% if c.business %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.investor %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.pension %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.visa_run %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.specialist %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">{{ c.happiness|default:"" }}</td>
                        <td class="text-center">{{ c.prosperity|default:"" }}</td>
                        <td class="text-center">{{ c.medicine|default:"" }}</td>
                        <td class="text-center">{{ c.summer|default:"" }}</td>
                        <td class="text-center">{{ c.winter|default:"" }}</td>
                        <td class="text-center">
                            {% if c.mountains %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.sea  %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div style="overflow-y: auto;"  id="countries_list">
        <table class="table table-bordered" >
            <thead>
                <tr>
                    <th rowspan="2">Страна</th>
                    <th colspan="5">Типы виз</th>
                    <th colspan="3">Индексы <small>(меньше - лучше)</small></th>
                    <th colspan="2">Температура</th>
                    <th colspan="2">Природа</th>
                </tr>
                <tr>
                    <th>Бизнес</th>
                    <th>Инвестиции</th>
                    <th>Рантье</th>
                    <th>Visa-run</th>
                    <th>Специалист</th>
                    <th><a href="https://ru.wikipedia.org/wiki/Международный_индекс_счастья">Счастья</a></th>
                    <th><a href="http://en.wikipedia.org/wiki/Legatum_Prosperity_Index">Prosperity</a></th>
                    <th><a href="http://en.wikipedia.org/wiki/World_Health_Organization_ranking_of_health_systems_in_2000">WHO rank</a></th>
                    <th>Летом</th>
                    <th>Зимой</th>
                    <th>Горы</th>
                    <th>Море</th>
                </tr>
            </thead>
            <tbody>
                {% for c in country_list %}
                    <tr>
                        <td><a href="{% url 'country' c.pk %}">{{ c.name }}</a></td>
                        <td class="text-center">
                            {% if c.business %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.investor %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.pension %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.visa_run %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.specialist %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">{{ c.happiness|default:"" }}</td>
                        <td class="text-center">{{ c.prosperity|default:"" }}</td>
                        <td class="text-center">{{ c.medicine|default:"" }}</td>
                        <td class="text-center">{{ c.summer|default:"" }}</td>
                        <td class="text-center">{{ c.winter|default:"" }}</td>
                        <td class="text-center">
                            {% if c.mountains %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                        <td class="text-center">
                            {% if c.sea  %}<span class="text-success glyphicon glyphicon-ok"></span>{% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

{% block js %}
    <script>
        $(function() {
            var header_height = $('#countries_header thead').height();
            $('#countries_header').height(header_height + 'px');
            $('#countries_list table').css('margin-top', (0 - header_height) + 'px');
            $('#countries_list').height($(window).height() - 200);

            $(window).resize(function() {
                $('#countries_list').height($(window).height() - 200);
            });
        });
    </script>
{% endblock js %}

kv/templates/upload.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputFile">XLSX</label>
            <input type="file" id="exampleInputFile" name="xls">

            <p class="help-block">Excel файл из <a href="https://docs.google.com/spreadsheets/d/1TLQNJBSFBRcjHuwWuO34vfgWtv1-XqvOjM2qHDzk9nc/edit#gid=0">специальной таблички</a>.</p>
        </div>
        <button type="submit" class="btn btn-default">Загрузить</button>
    </form>
{% endblock content %}

{% block js %}
{% endblock js %}